version: '3'

dotenv: ['.env']

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all
    silent: true

  login:
    desc: Login to Azure
    cmds:
      - |
        az login --tenant ${ARM_TENANT_ID}
        az account set --subscription ${ARM_SUBSCRIPTION_ID}
        az account show

  run-tests:
    desc: Run Terraform unit tests
    aliases: [test]
    cmds:
      - echo "Running Terraform tests..."
      - terraform test
      - echo "All tests passed!"

  validate:
    desc: Validate Terraform configuration
    cmds:
      - terraform fmt -check -recursive
      - terraform validate